### ISSUE TITLE
Error when importing shapely Python package

### ISSUE THREAD

**Issue by keballantyne** [eodms-sgdot/eodms-rapi-orderdownload#15]
Traceback (most recent call last):
  File "eodms_orderdownload.py", line 58, in <module>
    from utils import eod as eod_util
  File "/root/eodms-rapi-orderdownload/utils/__init__.py", line 1, in <module>
    from . import spatial
  File "/root/eodms-rapi-orderdownload/utils/spatial.py", line 33, in <module>
    import shapely.wkt
  File "/usr/local/lib/python3.6/site-packages/shapely/wkt.py", line 6, in <module>
    from shapely import geos
  File "/usr/local/lib/python3.6/site-packages/shapely/geos.py", line 99, in <module>
    _lgeos = load_dll('geos_c', fallbacks=alt_paths)
  File "/usr/local/lib/python3.6/site-packages/shapely/geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so'].

**Comment by keballantyne** [comment]
There are a few solutions to this issue listed at https://localcoder.org/could-not-find-library-geos-c-or-load-any-of-its-variants
