### ISSUE TITLE
Error when using existing CSV results

### ISSUE THREAD

**Issue by keballantyne** [eodms-sgdot/eodms-rapi-orderdownload#17]
Traceback (most recent call last):
  File "C:\Working\Development\EODMS\_old_projects\eodms-rapi-orderdownload\dev\eodms_orderdownload.py", line 1472, in cli
    prmpt.prompt()
  File "C:\Working\Development\EODMS\_old_projects\eodms-rapi-orderdownload\dev\eodms_orderdownload.py", line 1177, in prompt
    self.eod.download_only(self.params)
  File "C:\Working\Development\EODMS\_old_projects\eodms-rapi-orderdownload\dev\utils\eod.py", line 1951, in download_only
    query_imgs = self._get_prev_res(csv_fn)
  File "C:\Working\Development\EODMS\_old_projects\eodms-rapi-orderdownload\dev\utils\eod.py", line 479, in _get_prev_res
    csv_res = eodms_csv.import_csv()
  File "C:\Working\Development\EODMS\_old_projects\eodms-rapi-orderdownload\dev\utils\csv_util.py", line 309, in import_csv
    rec[self.header[i]] = c
TypeError: 'NoneType' object is not subscriptable

**Comment by keballantyne** [comment]
Fixed in version 2.5.2.
